"""Initial migration

Revision ID: 4645ed62d72d
Revises: 
Create Date: 2025-07-28 19:02:54.750179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4645ed62d72d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(length=80), nullable=False),
    sa.Column('long_url', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('url_entries')
    # ### end Alembic commands ###
